# Generated by Django 5.2.8 on 2025-11-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentesaude',
            name='area_coordenadas',
            field=models.JSONField(blank=True, help_text='Lista de coordenadas [lat, lng]', null=True, verbose_name='Coordenadas da Área (polígono)'),
        ),
        migrations.AddField(
            model_name='agentesaude',
            name='area_nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome da Área'),
        ),
    ]
