# Generated by Django 5.2.7 on 2025-11-04 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pacientes/')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.IntegerField()),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('pessoas_na_casa', models.IntegerField(blank=True, null=True, verbose_name='Qtd. pessoas na casa')),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('endereco', models.TextField()),
                ('comorbidade', models.BooleanField(default=False)),
                ('comorbidade_tipo', models.TextField(blank=True)),
                ('teve_avc', models.BooleanField(default=False, verbose_name='Teve AVC')),
                ('teve_infarto', models.BooleanField(default=False, verbose_name='Teve Infarto')),
                ('bebe', models.BooleanField(default=False, verbose_name='Bebe álcool')),
                ('tipo_bebida', models.CharField(blank=True, max_length=100)),
                ('fuma', models.BooleanField(default=False)),
                ('cigarros_por_dia', models.IntegerField(default=0)),
                ('anos_fumando', models.IntegerField(default=0)),
                ('medicamentos', models.TextField(blank=True, verbose_name='Medicamentos em uso')),
                ('alergia', models.BooleanField(default=False, verbose_name='Possui alergia')),
                ('alergia_tipo', models.TextField(blank=True, verbose_name='Tipo de alergia')),
                ('atividade_fisica', models.BooleanField(default=False, verbose_name='Pratica atividade física')),
                ('atividade_tipo', models.CharField(blank=True, max_length=200, verbose_name='Tipo de exercício')),
                ('atividade_frequencia', models.CharField(blank=True, max_length=100, verbose_name='Frequência')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='accounts.agentesaude')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paciente_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-criado_em'],
            },
        ),
    ]
