# Generated by Django 5.2.8 on 2025-11-13 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_agentesaude_area_coordenadas_agentesaude_area_nome'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='doenca_atual',
            field=models.CharField(blank=True, max_length=200, verbose_name='Doença ou Infecção Atual'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='is_contagiosa',
            field=models.BooleanField(default=False, verbose_name='É contagiosa'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='is_cronica',
            field=models.BooleanField(default=False, verbose_name='É doença crônica'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='is_infantil',
            field=models.BooleanField(default=False, verbose_name='É criança/adolescente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='medicamentos_prescritos',
            field=models.BooleanField(default=False, verbose_name='Necessita prescrição médica'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='necessidades_basicas',
            field=models.TextField(blank=True, verbose_name='Necessidades Básicas (fraldas, visita domiciliar, etc)'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nivel_gravidade',
            field=models.CharField(blank=True, choices=[('LEVE', 'Leve'), ('MODERADA', 'Moderada'), ('GRAVE', 'Grave'), ('CRITICA', 'Crítica')], max_length=10, verbose_name='Nível de Gravidade'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='prontuario_completo',
            field=models.TextField(blank=True, help_text='Informações sigilosas', verbose_name='Prontuário Completo'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='proxima_consulta',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima Consulta Agendada'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='recebe_auxilio_governo',
            field=models.BooleanField(default=False, verbose_name='Recebe auxílio do governo'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tem_acamado',
            field=models.BooleanField(default=False, verbose_name='Tem alguém acamado'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_auxilio',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tipo de auxílio'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_sanguineo',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Tipo Sanguíneo'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ultima_consulta',
            field=models.DateField(blank=True, null=True, verbose_name='Última Consulta'),
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco_completo', models.CharField(max_length=300)),
                ('cidade', models.CharField(default='Aracaju', max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('status', models.CharField(choices=[('CADASTRADA', 'Cadastrada'), ('NAO_CADASTRADA', 'Não Cadastrada'), ('PENDENTE', 'Pendente')], default='NAO_CADASTRADA', max_length=20)),
                ('qtd_moradores', models.IntegerField(default=0, verbose_name='Quantidade de Moradores')),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residencias', to='accounts.agentesaude')),
            ],
            options={
                'verbose_name': 'Residência',
                'verbose_name_plural': 'Residências',
                'ordering': ['bairro', 'endereco_completo'],
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='residencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moradores', to='patients.residencia'),
        ),
    ]
